### ISSUE TITLE
Set NEVNTMAX

### ISSUE THREAD

**Issue by brendan-mills** [SCEDC/pystp#4]
Hello! I am using Pystp to load a catalog of recent local earthquakes. I am trying to load a week's worth of earthquakes. But, in my queries I am running up against the default 100 event maximum. I know in the standalone STP there is way to set the NEVNTSMAX but I don't know how to use the pystp package to do this. Any help would be appreciated.

**Comment by shang-lin** [comment]
Hi Brendan,

PySTP currently doesn't support the "set" command that is used to change settings like NEVNTSMAX. I will work on adding it in the coming week. 

Shang-Lin
